### ISSUE TITLE
Alcuni messaggi di errore/successo non vengono mostrati

### ISSUE THREAD

**Issue by CatignanoFrancesco** [GiannettaGerardo/TicketYourTest#110]
Dopo il successo della compilazione del questionario anamnesi (o della prenotazione) non vengono mostrati i messaggi di errore o successo a causa del cambio della pagina di redirect dopo queste operazioni.

**Comment by GiannettaGerardo** [comment]
Nella view formCheckout manca il controllo sul messaggio di errore checkout-error, infatti l'errore non viene mostrato
