### ISSUE TITLE
Durante la registrazione del laboratorio non viene acquisito l'indirizzo

### ISSUE THREAD

**Issue by CatignanoFrancesco** [GiannettaGerardo/TicketYourTest#12]
Durante la fase di registrazione del laboratorio, quando viene richiesto l'indirizzo, non viene acquisito correttamente generando un errore.

**Comment by CatignanoFrancesco** [comment]
Nonostante l'aggiunta della riga mancante, l'errore persiste. Probabilmente il problema è dovuto alla mancanza degli attributi name e id nella rispettiva view.

**Comment by FrancolinoFlavioDomenico** [comment]
nonostante l'aggiunta degli attributo name mancante ad alcuni input la registrazione restituisce errori di convalida
