### ISSUE TITLE
Il doppio click sulla prenotazione fa presentare un errore

### ISSUE THREAD

**Issue by CatignanoFrancesco** [GiannettaGerardo/TicketYourTest#123]
Quando si fa doppio click sul tasto "conferma prentoazione", il sistema tenta di rifare la stessa prenotazione, restituendo un errore. La restituzione dell'errore, però, permette di creare la prenotazione una sola volta, ma non permette di accedere alla pagina di pagamento.

**Comment by CatignanoFrancesco** [comment]
I bug si presentano in tutte le tipologie di prenotazione.

**Comment by FrancolinoFlavioDomenico** [comment]
il fix non ha funzionato
