### ISSUE TITLE
Caso d'uso IF-CP.02 (inserimentoInListaDipendenti)

### ISSUE THREAD

**Issue by CatignanoFrancesco** [GiannettaGerardo/TicketYourTest#14]
Redmine Issue #120137

Issue relativa al caso d'uso sull'inserimento nella lista dei dipendenti del cittadino privato.

**Comment by fab0ba17** [comment]
L'ultima commit effettuata dal sottoscritto, relativa alla modifica del messaggio d'errore nel momento in cui viene inserito un dipendente che è già all'interno della lista dei dipendenti, fa riferimento al caso d'uso [**IF-DL.03 (aggiungiDipendentiAllaLista) #21]**.
