### ISSUE TITLE
Caso d'uso IF-DL.04 (eliminaDipendenteDallaLista)

### ISSUE THREAD

**Issue by CatignanoFrancesco** [GiannettaGerardo/TicketYourTest#24]
Redmine issue 120137 #10

Caso d'uso relativo alla possibilità per un datore di lavoro di eliminare un dipendente dalla lista.

**Comment by fab0ba17** [comment]
La seguente issue è stata ri-aperta per poter effettuare una modifica relativa all'inserimento di un messaggio di azione eseguita
